# Python imports
from time import sleep
from os import system
import random
# Custom imports
from characters import character_factory
from boss import FinalBoss

system("clear")
print("""
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0xooOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdoooodkd:c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKxollodOXWMMMMNx:lKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMWXkollokKWMMMMMMMMMMMKc:KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMW0dllokKWMMMMMMMMMMMMMMMMX:cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMW0dlld0NMMMMMMMMMMMMMMMMMMMMM0;lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMXxlcdKWMMMMMMMMMMMMMMMMMMMMMMMMWk,dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMXd:lONMMMMMMMMMWK0XMMMMMMMMMMMMMMMWd;kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMNx:l0WMMMMMMMMMMXl..xMMMMMMMMMMMMMMMMNl;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMKc:OWMMMMMMMMMMMMO' .kMMMMMMMMMMMMMMMMMXccXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMK:cXMMMMWNNMMMMMMMKolkNMMMMMMMMMWNXKOkxdo:,:oKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMNc.xMMMMXo,xWMMMMMMMMMMMMWNKOxdooooooodxkO0K0::KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMM0'.xMMMM0'.dWMMMMMMWXOxoooooodxO0XNWMMMMMMMMMK;lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMM0'.xMMMMXxxXMMWXOdoooodk0XWMMMMMMMMXkoodkXWMMNccNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMNc.xMMMMMMWKxolloxOXWMMMMMN0kx0NMWk:cxOkl:kWMWo;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMk,xMMMNOollokKWMMMXOk0NMKccddcc0X:cNMMMWl;KMMK:cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMO,xW0oclxKWMNK0NMO:co:cKo,0MMK;oK;oWMMMWo;KMMMk,xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMO,:lcdKNXNW0cclckl:KMO;xo;0MMX:oK;lWMMMWo;KMMMWo;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMk',xNMOclcdl,OX:cl:KMO;xo;KMMX:lK;lWMMMWo;KMMWW0;cKNXXXXWMMMMMMMMMMMMMXdodoooododdxxkkOO0KXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMWO;:ddxKl;Ko;:;OX:cl:XMO;xo;KMWK;:x';xxdoo;'coodddc:loooocc0MMMMMMMMMMMMO,l0OOOOkkkxxxl:;cooooooooodxkOKNWMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMK,.;;l::::Xd;:;OX:cl:0Xd':;.coooccooodxkkO0KKKXNNNWWWWWMMXc,coddddddddddc':doodoo0MMMWd,;:OMMWNXK0OxooooooooxOXWMMMMMMMMMMMMMMMMMM
MMMMMMMMMMO..,:0d;;:Kd;:,dd'';;looodkO0KXWWMMMMMMMMMMMMMMMMMMMMMMMMMk''l00000000000000000x'oMMMWo,c;kMMMMMMMMk::dXWX0kdooooxKWMMMMMMMMMMMMMM
MMMMMMMMMMX;.,:0d;;;d:';:loxO0XWMMMMMMMMMMMMMMMWXXWMMMMMWKxddkXWMMMMk'.ckkkkkkkkkkkkkkkkko'oMMMM0oloKMMMMMMMMd'';KMMMMWOldkollxXMMMMMMMMMMMM
MMMMMMMMMMMx'';xc.,:lxOKWMMMMWWMMMMMNkoodONMWKolooloKMMKl:dxxl:dNMMM0, 'oddddddddddddddddc.oMMMMMMMMMMMMMMMMMKocdNMMMMWo :XMN0l:xNMMMMMMMMMM
MMMMMMMMMMMk'.':okKWMWXKNWMNkloooKM0::xOx:cK0;cXWWK::KWl;KMMMWx,kMMMWd',cood0WMMW0dooodKWXc;dxxkkkOO0KKXNNWMMMMMMMMMMMMO:oNMMMWO:cXMMMMMMMMM
MMMMMMMMMMNl'cOXXXWMKlcocdXx,xXK::Kd,OMMMk;kk;kMMMMx;ONc:XMMMMO;dMMMMNKc'x0o;dNNd;o0KOl;kWO',ddddoooooooddooooodxk0KNWMMWWWMMMMM0;lNMMMMMMMM
MMMMMMMMMNl.cN0ccclKd;0Md,ko:XMMd,Od,OMMMk;kk;kMMMMx;ONc:NMMMMO;dMMMMMMK;lNWo;00;lWMMMNccNWx,kWMKoolxXWKdllx0Ooccloooooodk0NWMMMWo,0MMMMMMMM
MMMMMMMMMX; lWo;Kk,xo:KMk,ko:KMMd,Od,0MMMk;xk;kMMMMx;ONc:XMMMMO;dMMMMMMMk,dWd,00;oMMMMNlcNMNl;0Wc;0x,x0;:kl,xd:oclKOoclxxoooookKWx,kMMMMMMMM
MMMMMMMMMWO'lWo;Kk,xo:KMx,ko:KMMd,Od;0MMMk;xk;kMMMMx;ONc:XMMMMO;dMMWWWWWNo;Oo,O0;oWWWWNc:XWWK:cKc:XO,dk,xM0;c:lWx;l;cl,xkllokxoll;'kMMMMMMMM
MMMMMMMMMMX:lWo;Kk,xo:KMk,ko:KWNl'dl'dOkkl'cc.cxddd:'co,,lddooc,:doooooodl;cc;ll''loooo::oooo:;c::ol':d;xMO;c:oWx;c;dk;l;ld,dOoll;'kMMMMMMMM
MMMMMMMMMMX:lWo;Od'c:'ld:'::;ldolclllooooddddxkkkkOOOOO0000KKKKXXXXXXXXXXNNNNNNNo,kNXNNNNNNNNNNNNNNNd;l;xMO;c:oWx;c;dk;c;dO;l:;::l;kMMMMMMMM
MMMMMMMMMMX;,o:;oolodxkOO0KXXNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd,xKKKKKKKKKKKKKKKKKl;l;xMO;c:oWx;c;dk;c;dO:l:lo;c;kMMMMMMMM
MMMMMMMMMWx.;kKXWMMMMMMMMMMMWX00XWMMW0xdxONMMWXkddx0WMMMNOdood0NMMMMNOxdood0WMMMd.cooooooooooooooooo;.,.:xl',':0l';,dx;c;dO:l:lo;c;kMMMMMMMM
MMMMMMMMMNl.dMMWKKWMW0oooOWXocoocdXKl:dkd:lKNd:lxko:lKMKc:xOOd:lKMMKc:lxOOd:lKMMk,lxddkXMMMMXkddd0NMx,ldc:lddooolcc:lc,;';c';,cl;c;kMMMMMMMM
MMMMMMMMMM0,dMKlccc00;c0c,0x,kMWx,kx,kMMMO,dO,dWMMM0;dWl;KMMMM0;oMWl;KMMMMM0;oWMWd.;xxc:kWWk:cxkd:lKk,;clocdNKdoodXNkllxOxcclcl:;,'kMMMMMMMM
MMMMMMMMMMK;oMd,kO,dO;xMd,Od,OMMO;xd,OMMM0,dx;kMMMMX:oNc:XMMMMX:lWNc:XMMMMMX;lWMMWx;xWNc:XK;cNMMM0,oNl.lWMd;kc;0O;lx,l::0l;;d0ocxl'kMMMMMMMM
MMMMMMMMMMK;oMd,O0;dO;dMd,Od,OMMO;xd,OMMM0,dx;kMMMMX:oNc:XMMMMX:lWNc:XMMMMMX;lWMMMWx;xNl;KK;lWMMMK;oWXc:KMx;d:lWNccd;ko:x:l::c,'co,kMMMMMMMM
MMMMMMMMMMK;oMd,O0;dO;dMd,Od,OMMO;xd,OMMM0,dx;kMMMMX:oNc:XMMMMX:lWNc:XMMMMMX;lWMMMMWx;dl;KK;lWMMMK;oMMK:cXx;d:lWNccd;ko:x:l::c:;co;kMMMMMMMM
MMMMMMMMMMK;oMd,O0;dO;xMd,Od,OMMO;xd,OMMM0;dx;kMMMMX:oNc:XMMMMX:lWNc:XMMMMMX:lWMMMMMWk;.;KK;lWMMMK;oWMM0;ld;x:lWNccd;ko:x:l::c:;co;kMMMMMMMM
MMMMMKddddl';d:.cl';c':d:.c:.cddc'::.cdddl';:'cddddl';o,'oddddl';do,'odddddl',dddddddd;..ll';ddddl';dddd:''':,;do,,;'c;':';,,,'',;':ddd0WMMM
MMMMMXOkOkOOOOOOOOOOOOOkOOOOOOOOOOOOOOOOOOOOOOOOOkkOOOOOOOOOOkOOOkOOOOOOOOOOOOkkkkOkOOOOOkOOOkOOOOOOkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOKWMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMKolllOWMMMMXdlllxNMMKdllllllllxNMWOlllloodxOXWMMMMXxlllkWMWOollllllllOW0oloKMMMMMMKolo0MMMXdlllkNMMMMMXxllkWMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMd    .xWMMX:    '0MMk.   .....:KMWc   ...   .:kWMM0'   :NMWl   ......lN0,  ;XMMMMX:  '0MMNc    .xWMMMM0'  :NMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMd   . .OWNl ..  ,0MMx.  :KKKKKXWMWc  .dKK0d,  .dNM0'   :NMWl  .oKKKKKNMWk.  lNMMNo  .xWMWd. .,. '0MMMM0'  :NMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMd  .o; ,Oo..l;  ,KMMx.  .;;;;;xWMWc  .kMMMMK,  .OM0'   :NMWl   ';;;;c0MMWo  .xWWx.  oNMWO. .dK:  :XMMM0'  :NMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMd  .k0' .. lXc  ,KMMx.  .,,,,;xWMWc  .kMMMMX;  .kM0'   :NMWl   .;,,,:0MMMX:  '0K,  :XMMK;  ;0Xx.  oNMM0'  :NMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMd  .kMk.  :XN:  ,KMMx.  lWMWMWMMMWc  .kMMWXl.  :XM0'   :NMWl  .kWWWWWMMMMM0,  ;;  '0MMNc   ....   .xWM0'  :NMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMd  .kMW0dxXMN:  ,KMMx.  .:::::oKMWc   ,::;.  .lKMM0'   :NMWl   ':::::xNMMMWk.    .xWMWd. .cddddd,  '0M0'  .;::::l0MMMMMMMMMM
MMMMMMMMMMMMMMMMO;':0MMMMMMMWd''lXMMO;'''''''':0MWx''''',;:lxKWMMMKc'''oNMWx'''''''''oXMMMMWd,'',dWMMXl''oNMMMMM0:',xWKc'''''''';OMMMMMMMMMM
MMMMMMMMMMMMMMMMWWNWWMMMMMMMMWWNWMMMWWNWNNWWNNWWMMWWNWWWWMMMMMMMMMMWNNNWMMMWWNNNNNWNWWMMMMMMWWWNWWMMMWWNWWMMMMMMMWNNWMWWNNNNNNNNWWMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM""")
print("Welcome, heros!")
print("You are on the quest to defeat the great and powerful Markus, the Master of Python!")

fighters = []

# MENU
for num in range(0, 3):
    fighters.append(character_factory())
    fighters[num].get_name(num+1)
    fighters[num].get_class()
    fighters[num].get_weapon()
    fighters[num].get_armor()

    print(f"Thank you {fighters[num].name} the {fighters[num].person} for your enlistment!")
    sleep(1)
    system("clear")
    if len(fighters) < 3:
        print(f"Now we have {len(fighters)} heroes enlisted:\n")
        for fighter in fighters:    
            print(fighter)
        print(f"\nWe need {3-len(fighters)} more heroes...")

# The list of fighter
enemy = FinalBoss()
system("clear")
print("So we have...\n")
for fighter in fighters:    
    print(fighter)
    sleep(0.5)
print("      VS\n")
sleep(0.5)
print(enemy)
input("\nAre you ready for battle ")
system("clear")

# Arena/battle engine
battle = True
turn = 0
print ("Let the fighting begin!\n")

while battle == True:
    if len(fighters) == 0: # Sopping the game if there are no more fighters left
        print("All Heroes are dead!\nMarkus the Beast kill you all!")
        break

    input("Are you ready for next turn? ")

    # Game turn
    turn += 1
    print(f"\n   --------------- Round {turn}: ---------------\n")

    # Character's turn
    for fighter in fighters:
        def_power = enemy.defend()
        att_power = fighter.attack()
        if (def_power - att_power) > 0:
            damage = 0
        else:
            damage = def_power - att_power
        print(f"{fighter.name} ({fighter.health}hp) attacks {enemy.name} with his {fighter.weapon.name}({att_power}).")
        print(f"{enemy.name} the Beast lost {damage} hp, and now has {enemy.health+damage}hp left.")
        enemy.health = enemy.health + damage
        sleep(0.5)

    # Checking if the boss is dead.
    if enemy.health <= 0:
        print("The heroes won!")
        break

    # Boss turn
    print()
    fighter = fighters[random.randint(0, len(fighters)-1)] # Random victim chose 
    def_power = fighter.defend()
    att_power = enemy.attack()
    if (def_power - att_power) > 0:
            damage = 0
    else:
        damage = def_power - att_power
    print(f"{enemy.name} ({enemy.health}hp) attacks {fighter.name} with his Krav Maga and brute force ({att_power}).")
    print(f"{fighter.name} the {fighter.person} lost {damage} hp and now has {fighter.health+damage} hp.")
    fighter.health = fighter.health + damage

    # Checking if someone is dead.
    if fighter.health <= 0:
        print(f"\n{fighter.name} the {fighter.person} is dead!")
        fighters.remove(fighter) # Removing the dead fighter from the list
    print()