start ="""
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0xooOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdoooodkd:c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKxollodOXWMMMMNx:lKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMWXkollokKWMMMMMMMMMMMKc:KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMW0dllokKWMMMMMMMMMMMMMMMMX:cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMW0dlld0NMMMMMMMMMMMMMMMMMMMMM0;lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMXxlcdKWMMMMMMMMMMMMMMMMMMMMMMMMWk,dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMXd:lONMMMMMMMMMWK0XMMMMMMMMMMMMMMMWd;kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMNx:l0WMMMMMMMMMMXl..xMMMMMMMMMMMMMMMMNl;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMKc:OWMMMMMMMMMMMMO' .kMMMMMMMMMMMMMMMMMXccXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMK:cXMMMMWNNMMMMMMMKolkNMMMMMMMMMWNXKOkxdo:,:oKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMNc.xMMMMXo,xWMMMMMMMMMMMMWNKOxdooooooodxkO0K0::KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMM0'.xMMMM0'.dWMMMMMMWXOxoooooodxO0XNWMMMMMMMMMK;lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMM0'.xMMMMXxxXMMWXOdoooodk0XWMMMMMMMMXkoodkXWMMNccNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMNc.xMMMMMMWKxolloxOXWMMMMMN0kx0NMWk:cxOkl:kWMWo;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMk,xMMMNOollokKWMMMXOk0NMKccddcc0X:cNMMMWl;KMMK:cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMO,xW0oclxKWMNK0NMO:co:cKo,0MMK;oK;oWMMMWo;KMMMk,xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMO,:lcdKNXNW0cclckl:KMO;xo;0MMX:oK;lWMMMWo;KMMMWo;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMk',xNMOclcdl,OX:cl:KMO;xo;KMMX:lK;lWMMMWo;KMMWW0;cKNXXXXWMMMMMMMMMMMMMXdodoooododdxxkkOO0KXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMWO;:ddxKl;Ko;:;OX:cl:XMO;xo;KMWK;:x';xxdoo;'coodddc:loooocc0MMMMMMMMMMMMO,l0OOOOkkkxxxl:;cooooooooodxkOKNWMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMK,.;;l::::Xd;:;OX:cl:0Xd':;.coooccooodxkkO0KKKXNNNWWWWWMMXc,coddddddddddc':doodoo0MMMWd,;:OMMWNXK0OxooooooooxOXWMMMMMMMMMMMMMMMMMM
MMMMMMMMMMO..,:0d;;:Kd;:,dd'';;looodkO0KXWWMMMMMMMMMMMMMMMMMMMMMMMMMk''l00000000000000000x'oMMMWo,c;kMMMMMMMMk::dXWX0kdooooxKWMMMMMMMMMMMMMM
MMMMMMMMMMX;.,:0d;;;d:';:loxO0XWMMMMMMMMMMMMMMMWXXWMMMMMWKxddkXWMMMMk'.ckkkkkkkkkkkkkkkkko'oMMMM0oloKMMMMMMMMd'';KMMMMWOldkollxXMMMMMMMMMMMM
MMMMMMMMMMMx'';xc.,:lxOKWMMMMWWMMMMMNkoodONMWKolooloKMMKl:dxxl:dNMMM0, 'oddddddddddddddddc.oMMMMMMMMMMMMMMMMMKocdNMMMMWo :XMN0l:xNMMMMMMMMMM
MMMMMMMMMMMk'.':okKWMWXKNWMNkloooKM0::xOx:cK0;cXWWK::KWl;KMMMWx,kMMMWd',cood0WMMW0dooodKWXc;dxxkkkOO0KKXNNWMMMMMMMMMMMMO:oNMMMWO:cXMMMMMMMMM
MMMMMMMMMMNl'cOXXXWMKlcocdXx,xXK::Kd,OMMMk;kk;kMMMMx;ONc:XMMMMO;dMMMMNKc'x0o;dNNd;o0KOl;kWO',ddddoooooooddooooodxk0KNWMMWWWMMMMM0;lNMMMMMMMM
MMMMMMMMMNl.cN0ccclKd;0Md,ko:XMMd,Od,OMMMk;kk;kMMMMx;ONc:NMMMMO;dMMMMMMK;lNWo;00;lWMMMNccNWx,kWMKoolxXWKdllx0Ooccloooooodk0NWMMMWo,0MMMMMMMM
MMMMMMMMMX; lWo;Kk,xo:KMk,ko:KMMd,Od,0MMMk;xk;kMMMMx;ONc:XMMMMO;dMMMMMMMk,dWd,00;oMMMMNlcNMNl;0Wc;0x,x0;:kl,xd:oclKOoclxxoooookKWx,kMMMMMMMM
MMMMMMMMMWO'lWo;Kk,xo:KMx,ko:KMMd,Od;0MMMk;xk;kMMMMx;ONc:XMMMMO;dMMWWWWWNo;Oo,O0;oWWWWNc:XWWK:cKc:XO,dk,xM0;c:lWx;l;cl,xkllokxoll;'kMMMMMMMM
MMMMMMMMMMX:lWo;Kk,xo:KMk,ko:KWNl'dl'dOkkl'cc.cxddd:'co,,lddooc,:doooooodl;cc;ll''loooo::oooo:;c::ol':d;xMO;c:oWx;c;dk;l;ld,dOoll;'kMMMMMMMM
MMMMMMMMMMX:lWo;Od'c:'ld:'::;ldolclllooooddddxkkkkOOOOO0000KKKKXXXXXXXXXXNNNNNNNo,kNXNNNNNNNNNNNNNNNd;l;xMO;c:oWx;c;dk;c;dO;l:;::l;kMMMMMMMM
MMMMMMMMMMX;,o:;oolodxkOO0KXXNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd,xKKKKKKKKKKKKKKKKKl;l;xMO;c:oWx;c;dk;c;dO:l:lo;c;kMMMMMMMM
MMMMMMMMMWx.;kKXWMMMMMMMMMMMWX00XWMMW0xdxONMMWXkddx0WMMMNOdood0NMMMMNOxdood0WMMMd.cooooooooooooooooo;.,.:xl',':0l';,dx;c;dO:l:lo;c;kMMMMMMMM
MMMMMMMMMNl.dMMWKKWMW0oooOWXocoocdXKl:dkd:lKNd:lxko:lKMKc:xOOd:lKMMKc:lxOOd:lKMMk,lxddkXMMMMXkddd0NMx,ldc:lddooolcc:lc,;';c';,cl;c;kMMMMMMMM
MMMMMMMMMM0,dMKlccc00;c0c,0x,kMWx,kx,kMMMO,dO,dWMMM0;dWl;KMMMM0;oMWl;KMMMMM0;oWMWd.;xxc:kWWk:cxkd:lKk,;clocdNKdoodXNkllxOxcclcl:;,'kMMMMMMMM
MMMMMMMMMMK;oMd,kO,dO;xMd,Od,OMMO;xd,OMMM0,dx;kMMMMX:oNc:XMMMMX:lWNc:XMMMMMX;lWMMWx;xWNc:XK;cNMMM0,oNl.lWMd;kc;0O;lx,l::0l;;d0ocxl'kMMMMMMMM
MMMMMMMMMMK;oMd,O0;dO;dMd,Od,OMMO;xd,OMMM0,dx;kMMMMX:oNc:XMMMMX:lWNc:XMMMMMX;lWMMMWx;xNl;KK;lWMMMK;oWXc:KMx;d:lWNccd;ko:x:l::c,'co,kMMMMMMMM
MMMMMMMMMMK;oMd,O0;dO;dMd,Od,OMMO;xd,OMMM0,dx;kMMMMX:oNc:XMMMMX:lWNc:XMMMMMX;lWMMMMWx;dl;KK;lWMMMK;oMMK:cXx;d:lWNccd;ko:x:l::c:;co;kMMMMMMMM
MMMMMMMMMMK;oMd,O0;dO;xMd,Od,OMMO;xd,OMMM0;dx;kMMMMX:oNc:XMMMMX:lWNc:XMMMMMX:lWMMMMMWk;.;KK;lWMMMK;oWMM0;ld;x:lWNccd;ko:x:l::c:;co;kMMMMMMMM
MMMMMKddddl';d:.cl';c':d:.c:.cddc'::.cdddl';:'cddddl';o,'oddddl';do,'odddddl',dddddddd;..ll';ddddl';dddd:''':,;do,,;'c;':';,,,'',;':ddd0WMMM
MMMMMXOkOkOOOOOOOOOOOOOkOOOOOOOOOOOOOOOOOOOOOOOOOkkOOOOOOOOOOkOOOkOOOOOOOOOOOOkkkkOkOOOOOkOOOkOOOOOOkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOKWMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMKolllOWMMMMXdlllxNMMKdllllllllxNMWOlllloodxOXWMMMMXxlllkWMWOollllllllOW0oloKMMMMMMKolo0MMMXdlllkNMMMMMXxllkWMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMd    .xWMMX:    '0MMk.   .....:KMWc   ...   .:kWMM0'   :NMWl   ......lN0,  ;XMMMMX:  '0MMNc    .xWMMMM0'  :NMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMd   . .OWNl ..  ,0MMx.  :KKKKKXWMWc  .dKK0d,  .dNM0'   :NMWl  .oKKKKKNMWk.  lNMMNo  .xWMWd. .,. '0MMMM0'  :NMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMd  .o; ,Oo..l;  ,KMMx.  .;;;;;xWMWc  .kMMMMK,  .OM0'   :NMWl   ';;;;c0MMWo  .xWWx.  oNMWO. .dK:  :XMMM0'  :NMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMd  .k0' .. lXc  ,KMMx.  .,,,,;xWMWc  .kMMMMX;  .kM0'   :NMWl   .;,,,:0MMMX:  '0K,  :XMMK;  ;0Xx.  oNMM0'  :NMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMd  .kMk.  :XN:  ,KMMx.  lWMWMWMMMWc  .kMMWXl.  :XM0'   :NMWl  .kWWWWWMMMMM0,  ;;  '0MMNc   ....   .xWM0'  :NMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMd  .kMW0dxXMN:  ,KMMx.  .:::::oKMWc   ,::;.  .lKMM0'   :NMWl   ':::::xNMMMWk.    .xWMWd. .cddddd,  '0M0'  .;::::l0MMMMMMMMMM
MMMMMMMMMMMMMMMMO;':0MMMMMMMWd''lXMMO;'''''''':0MWx''''',;:lxKWMMMKc'''oNMWx'''''''''oXMMMMWd,'',dWMMXl''oNMMMMM0:',xWKc'''''''';OMMMMMMMMMM
MMMMMMMMMMMMMMMMWWNWWMMMMMMMMWWNWMMMWWNWNNWWNNWWMMWWNWWWWMMMMMMMMMMWNNNWMMMWWNNNNNWNWWMMMMMMWWWNWWMMMWWNWWMMMMMMMWNNWMWWNNNNNNNNWWMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"""

heroes_won = """
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0Okxxk0NMMMMMMMMMMMMMMMMMMMMMWWNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMN0OOOddkOKWMMMMMMMMMMMMWWNXK0OOO00KXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0OWMMMMMMMMMMMMMWKOOOxdoxk0XMMMMWWNXK0OOkkxxkO0KNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKkXMMMMMMMMMMMMMWKxdlcccldx0K0OkkxdddxkOKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO0MMMMMMMMMMMMMWKxdocclloddoodkO0KXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKOXMMMMWWNX0Oxdl;,'''':lllood0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXxk0Okxxxoc:,'.......:ddlclllx0XNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0KNNX0kxlc:,;:clo:,''''''''cxxxkkxlccodx0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKkoccoo:;:ll;,okOOd:';::llcllox0KKkc,,,:cc:cOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXXNXKK0kdl:,,;,,,'lKWNkdXMNd..;kkxkxodxxkxdc'....;c::;oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk:::cldxxO00d;'....;dkOkokOc,..:kOkxdk0KK0kxl'. .,okdlokXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKocd0NWMMMMMMN0xc,';::ldl:'....,odddxO0KKKKOxc...,:ldllxkXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNWMMMMMMMMMMMMWKOkoccdl;......:ooodO0000Oxoc,...'cOOoc;xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0dol,.....:oxdloxdoxOxo:,,;ldc:ododdxXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNKOdox0Kxddcldl;:c:;'.';kNd,:xKKOxKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNkc;;;,,;:;'',;,,,dWXo:dK0doKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0l:ccc:clk0k:',:c;,:ON0coKXkkNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk:;,'.,,:ldo:'',,'.':kW0okX00WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXxl:'...',,,;;;,'''..';loodK0ONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0o;..........';c;'''.....:dkoo0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNxc'...........:k0x:'...'cok0xdKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXko;.............,:c;...,cclxxol0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXOo;...............   .';colclcl0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNWMWx'....................'dx:,,cOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNWMMNo......................:oldOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNWMMXc.''''..''''''.........:0WWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMWO:;;;;,;;;;;:;;;;;;;;;;oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKoc:::::::lxOd:::c:::::dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKxdollllldKWWKxooxxdoldKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXkkkxxddokNMMMKkxOOkkxkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXOOOOOkxdxKWMMNOOO0OkkO0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0OOO0OxxOXMMMMXO000OO00O0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWK000K0Ok0NMMMMN00000000XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNK00KK0OKWMMMMWXK0KKKKKKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKKKKK0XMMMMMMWXKKXXXKKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNXXXXKXWMMMMMMMWXXXXXXXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXNXXXNMMMMMMMMMWXXXXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNXNWMMMMMMMMMMNNNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMWWNNWMMMWNNWMMWNNNNNNNWMMWWNNNNWWMMMMMMMMWNXNNWMMMMMWNNNNNXXNNNWMWNNXXNWMMWNNWNWWNNWMMMWNNWMMMWWNWMMMMWWNXNWMMMMMWNNWWMMMWNNWMMMWNWMMMMM
MMMMKc':0MMMk,'dWMk,''''''lXM0:'',,,;cOWMMWOl;,,,,;oKWMNo'''''''dNWKo,'',,,,dNMWWWWWXc'cKMWk,'cKMWk,'xWMKd;,,,',cONMMO;''dNMWd';OMMXl'cKMMMM
MMMM0' .OMMMd  :NMd. 'dxxx0NMk. .okl. '0MNo. ,x0Od. .xWN:  ;xxxxKWN: .'l00OxOWMWWWWWWl  dWX;  .oWX; .OWO' .lO0x;  lXMd.  .lNWc .dMMK, '0MMMM
MMMM0'  ,ccc'  :NMd. .:ccckWMk. .oxc..lXMO. .OMMMMd. ,KN:  'cccl0MNl  ..:cokXWMMMMMMMO. ,Kx.;o.,Kx. cNX:  oWMMM0' .xMd. ',.lXc .xMMK; ,KMMMM
MMMM0'  ;ccc'  :NMd. .:lcckWMk.  .'  ,0MMk. '0MMMMx. ,KN:  'lcco0MMNOolc;'  'kMMMMMMMNl .l;.dX;.l: .kMX;  dMMMMK, .xMd. l0;.:; .xMMNl.lNMMMM
MMMM0' .OMMMo  :NMx. ,O00KXWMk. 'ONd. 'OMXc  :0XXO, .oWN:  cKKK0XWW0kKXXX0;  oMMMMMMMMO. . ,KMd.   :NMWx. 'kXNKc. ;KMx. cWK;   .xMMNxcxNMMMM
MMMM0;.,OMMMd..lNMx....''':0MO'.;KMWx..:KMNx;..,,..:kNMNc...''''oNNo',,,,'..lKMMMMMMMMNl...dWMK:...xMMMWOc'.','.,dXMMx..oWMXc...xMMK: ;KMMMM
MMMMWX0KNMMMN00XMMNK000000KWMWK0KWMMWX00NMMMWX0O00XWMMMWX0000000XWMWXK00O00XWMMMMMMMMMMN00KNMMMX00KWMMMMMWNK0O0KWMMMMN00XMMMNK0KNMMWK0KWMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"""

game_over = """
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
MMWWWWWMMWWWWWMMWWNWMMMWWWWMMMWNWWMMMNXNWWMWWWWWMMWWNWWMMWWNWWMMWWWWMMMMWWWWMMWWNWWMMWWWWWMMWWWWWMMWNKNMMWWWNWMMWWWWWMMWWNWWMMWWNWWMMWWWWWMM
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNxOWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWOoKWWWWWWWWWWWWWWWWWWWWWWWWWMWWWWWWWWWWW
WWWWMMWWWWWWWWWWWMMWWWWWWWWWWWWWWWWWWWo;0WWWWWWWWWWWWMWWWWWWWWWWWMWWWWWWWWWWWWWWMWWWWWWWWWWWWMMWWWWK:;XWWWWMMWWWWWWWWWWWWWWWWWWWMWWWWWWMWWWW
MMWWNWWWMWNNWWMWWWNWMMWWWNWWMMWWNWMMWWd.:XMWWNNWMMWWWWWMMWWWWWMMWNNWMMMWWNNWMMMWWWWMMWWNNWMMWWWWWWNl :XMWWWWWWMMMWNWWMMWWWWWMMWWWWWMMWWWWMMM
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWx. cXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNo. lNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
NWWWMMWNNWMMWWWWWMMWWWWWMMWWNNWMMWWWWWO.  cXWMMWNWWMMMWNNWMMWWWWWMMWWNNWWMMWWWWWMMWWNWWMMWWNWMMMXl. .xWNNWWMMWWWWWMMWWWWWMMWWNWMMMWWWWMMWWNW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMWWK;   :KWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXc   .OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
MMWWWWWMMWWNWWMMWWNWWMMWNWWWMMWWWWMMWWNl    ,ONWMWWWWWWMMWWNWMMMWWWWWMMMWWWWWMWWWWWWMWWWWWMWWWO;    ;XWWWWWWWWMMMWWWWMMWWWWWWMWWWWWMMWWWWWMM
WWWMMMWWWWMMMWNWWWMWWWWWMMWWWWWMMWWWWWMO.    .dNWWWWMWWWWWMMWWWWWMMWWWWWWMMWWWWWMMWWWWMMWWWWNx.    .dWWWNWWMMWWWWWMMWWWWWMMWWWWWMMWWNWMMWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNc      ;0NWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW0:.     ,KWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
MMWWNWWMMWWWWWMMWWNWMMMWNNWMMMWWNWMMMWNWO'      .lKWOxNWNWWNWWMWWNNWMMMMWNNWMMMWNWWXNNxdXKo.      .xNNWWMMWNWWMMMWNNWMMWWNWWMMWWNWWMMWWNWWMM
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWx.       .l, cdo0WWWWWWWWWWWWWWWWWWWWWWWWXccc..:'       .oNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWMMMWWWWMMMWNWWMMWWWWWMMWWNWWMMWWNWWMWXKx.           ..oNWWWWWWMMWWWWWWMMWWNNWMWx..           .d00XMWNNWWWWWWNWWMMWWWWWMWWWNWMMMWWWWMMWWWN
WWWWWWWWWWWWWWWWWWWWWMWWWWWWWWWWWNKXWWWNo,c;.         ,xdxXWWWWWWWWWWWWWWWWWWWWWNN0O0l...       ';.:KWWWNOKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
MWWWWWWMWWWWWWWWWWWWWWWWWWWWWMWWXl'xWWWWx.         :kd0WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXO0d.         oNWWW0,'kNWWWWWWWWMWWWWWWWMWWWWWWWWWWWWWM
NNWMMMWWNWMMWWNWWMMWWNWWMMWWWWWX:  :XWWMK;    .:l;lKMWWNWWMMWWWWWMMWWNNWWMMWWNWWMMWWNWMMWkcox,    .xWWWNl  .kWWNWWMMWWWWMMWWWWWMMMWWWWMMMWNW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXc   .oNNk;  .  ;XWNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWo.... .cKNd.   '0WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
MMWWNWWMMWWNWMMMWWNWWMMWNWWWMMk.    .:c.  .xOokWMMWNXNWWWWWNWMMMWNNWWMMMWWWWMMMWWWWWNNWNWWMMWKx00;   ,;.     lWMWWWWWMMWWWWWMMWWWWWMMWWWWMMM
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWl           :XWWWWWWWWxxNWWWWWWWWWWWWWWWWWWWMWWWWWWWW0d0WWWWWWWWWWWd.          ;KWWWWWWWWWWMMWWWWWWWWWWWWWWWWW
WWWWMWWWWWMMWWWWWMMWWWWWMWWWWNc          ,0WKdoOXWWWO;:kXWWWWWWWWMMWWNNWWWWWWWWWWKd,oNMMN0doONWWWNo.         '0WWWMMWWWWWMMWWWWMMWWWWWMMMWWW
MWWWWWWWMWWWWWMWWWWWWMMWWWWWMWl         .ON0c.  ':dOXk..,oONWWWWWWWWWWWWWNWWWWKx:..lXKkl,.  'xXWWMN:         ;XMWWWWWWMMWWWWMMWWNWWMMWWWWMMM
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWk.        ;KMNo..    .'c:.  .'oKWWWWWWWMMWWWWNk:.   'c;.     .:0WWWWNc         oWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WNWMMMWWNWMMMWNWWMMWWNWWMMWWNWNd.       .cKNXKd;'            :XWWMMWWNNWWWWx.           .,lOKNMWN0l.       .oXWNWWMMWWWWMMMWNWWMMMWNNWMMWWNN
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNOo,.      ;ONWNNd.         'lOWWWWWWWWWWWWWKd;.         ;KNWWWWWKl.      'o0NWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
MMWWNWWMMWWWWWMMWWNWWMMWNWWWWWWXkc'      ,0WWWWWKc        'OWWMWWWWNXNWWWWWWMNl        'kNWWWWWNWNl      .,o0NWMWWWWWMMWWNWWMMWWNWWMMWWWWWMM
WWWWMWWWWWWWWWWWWWMWWWWWWWWWNWWKdoolc,   ,odONWWWNkl,.  .;OWWWWWWWXxoodONWWWWWKl.. ..:xXWWWWWWXklc,   ,ldkkx0NWWWWWMWWWWWMMWWWWWMWWWWWWMWWWW
WWWWWWWWWWWMWWWWWWWWWWWWMWWWWWWWWWWXk:.     .oKWWWWWNKOO0NWWWWWWNk;.....:OWWWWWWKOO0XWWWWWWWWNk,      'lONWWWWWWWWWWWWWWWMMWWWWWWWWWWWWWWWWW
MMMWNWWMMWWWWWMMWWNWMMMWWNWMMWWWWNk;...     .cxXWWWWNWWMMWWWWWWW0:',,,;;'c0WWMWWNNWMMWWNNWMMXxc'   ...'',oXWNWMMMWNNWMMWWNWWMMWWNWWMMWWNWMMM
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWN0O0000Oxl:.  'dXWWWWWWWWWWWNKo'.       ..lKWWWWWWWWWWWWWXd'  'cdk0XXNXK0XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWMMMWWNWMMWWWWWMMMWWWWMWWWWWWMMWWNWMMWWWWNXk:. 'kNMWWNWWWXd;.             .:o0WWWNNWWWWk, .ckNWNNWMMWWNNWMMWWNWWMMWWWWWMMWNWWMMMWNWWMMWWWW
WMWWWWWWWWWWWWWWWWWWWMWWWWWWWWWWWWWWWWWWWWWWNKOl. .lXWWWWWX:                   .xNWWWWWXo. .ck0XNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
MMWWWWWMMWWWWWMMWWNWWMWWWWWWMWWWWWWMWWWNKko:'.      'ld0NWK, .:xOkdc.   .cxOkl' ;KWWKxl,      ..;lx0XWWWWWWWWWWMMWWWWWWWWWWWWMWWWWWWWWWWWWMM
WWWMMMWWWWMMWWWWWWMWWWWWMMWWWWWMMWWWKkl;.              .;kNk:odllldO0xclxxolloocxN0l.              .'cd0XWWMMWWWWWMMWWWWWMMWWWWMMWWNWWMMWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWN0o;.       ......       .:l,.     .,lo:.      .cl.       ......       .,lkXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
MMWNNNWMMWWWWWMMWWWWMMMWWNWWMNOl,.   ..;coxOO00K0o.                                       ;k0000Okdl:'.    .:xKWWWNWWWMMWWWWMMWWWWWMMWWNNWMM
WWWXxONWWWWWWWWWWWWWWWWWWWXkl'   .,cd0XWWWWWWWWW0ol;                                    .llxNWWWWWWWWNKko;.   .:d0NWWWWWWWWWWWWWWWWWWWKx0WWW
WWWW0:cOXWWWWWWWWWWWWNX0xc'   .:d0NWWWMMWWWWWMMWNNNd,cl'    .cd,  ,l'  .::. .ld'    .:l;lKWNWMWWWWWWMMWWWNKkl,.  .;okKNWWMWWWNWWMWWNKd:dNWWW
MMWWW0l';ldO0KXXK0Oxo:'.   .:xKNWWWWWWWWWMMWWWWWWWWXNKc.    .lXKolKWKdlkNNxcONk'     'kNXNMMWWWWWMMWWWWWMWWWNXOl'.   .;ldkO0KXXKOko:';kNWWWM
WWWWWWW0d:'.......    .';lxKWWWWWWWWWWWWWMWWWWWMWWWWWk'     .oXWWWWWWWWWWWWWWWO,     .lXWWWWWWWWWMWWWWWWWWWWWWWWXOo:'.     ......',lkNWWWWWW
WNWMMMWWWWNKOxdoooodxk0XWMWWNWWWMWWWWWMWWWNWMMMWWNWMWXxl'   .dXWWWMWWNNWWMMWWNO;.  .:d0WWWNWWMMMWWWWMMWWWWWMMWWWWWMWNKOkxdooooxk0XNWNWMMMWWW
WWWWWWWWWWWWWWWMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWx.  ;0NKXWWWWWWMWWWN0XXo.  :NWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMWWWWWWWWWWWWWWW
MMWWWWWMMMWWWMMMWWWWWMMWWWWMMMWWWWMMWWWWWMMMWWWWMMWWWWWM0'  ,xc,OWWWWMMMWNWX:,dl.  oWWWWWWMMWWWWWMMWWWWWMMWWNWMMWWWWWWMMWNWWMMWWWWWMMWWWWMMM
WWWWWMWWWWWMWWWWWWMWWWWWMWWWWWWWMWWWWWWWWWWWMMWWWWWWWWWW0'  .. .kWWWWWWWWWWX; ..   oWWWWMWWWWMWWWWWWWWWWWWWWWWWWWWMMWWWWWWWWWWWWWWWWWWWMWWWW
WWWWMWWWWWWMWWWWWWMWWWWWMMWWWWWMWWWWWWWWWWWWMMWWWWWMMWWWx.      lNNK000K0XWk.      cXWWWMWWWWMMWWWWWMMWWWWWWWWWWWWMMWWWWWMWWWWWWWWWWWWWMWWWW
MMWWWWWMMWWNWWMMWWWWWMMWWWWMMMWWWWMMWWWWWMMWWWWWMMWWWWNk'       .,,......';.       .lXWWWWMMWWWWWMMWWWWWMMWNNWMMWWWWWMMWWWWWMMWWWWWMMWWWWWMM
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMWWWWNkc'                          .;oXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WNWMMMWWNWMMMWNWWMMMWNWWMMWWWWWMMWWWWWMMWWNWMMMWWWWMMWNNd.                         ;KNWMMWNNWMMMWWWWMMWWNWWMMWWNWWMMWWNWWMMWNNWMMMWWWWMMWWWN
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMNo:;..cdl,..       .':do' 'cl0WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
MWWWWWWWMWWWWWMMWWWWWMMWWWWWMMWWWWMMWWWWWMMWWWWWMMWWWWWWWWXdOWWWNK0OkkkkOO0XWWWKx0WWWWWWWWMMWWWWWMWWWNWWMMWWWWWMWWWWWMMWWWWWMMWWNWWMMWWWWWMM
WWWMMMWWWWWWWWWWWWMMWWWWMMWWNWWMMWWWWWMMWWNWWMWWNNWMMWWWWWWWWWWWWWMWWNWWWWWWWNWWWWWWWWWMMWWWWWMWWWWWMMWWWWWMMWWWWWMWWWWWWMMWWWWWMMWWWWMMWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMWWWWWWWWWWWWWWWWWWWWWWWWWWMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
MMMWWNK000XWWWMWX0O0XWWWWNWMMMWWNWMMWWNWWMMWWKxdkNWWNWWMMWWWWMMWWWNWMMWWWWWWMMWWWWWMMWWWWWMMWWNWMMMWWNWMMMWWNWMMMWNWWMMWWNWWMMWWNWWMMN0OKWMM
WWWWW0;...:KWWWK;...;KWWWWWWWWWWWWWWWWWWWWWWWk. '0WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWx..cNWW
NNWWM0'    lNWK:    ,0WWNKOkxkOKWWWWXOxOXKkkXk. 'OWN0xxONN0xkKWWNOxkXWNWNK0kxOKNMMWNNWMMNkdONMW0dkXWW0xxKWWMN0kxk0XWWWN0xx0N0kk0NMWWWd. :XWW
WWWWWO. .:..dXo ':. ,KMNd,,,''..:0WMO. .,;,,kk. 'OO:..c0WX; .xWWK, .kMWKc..'',,c0WWWMWWWK; .kWO. .xW0, '0MXo'..''..:0WWl  .:;...:KWWMx. :NMW
MMWWWO. .xx..;..kx. ,0MW0ollc:.  cNMO. .lKXXNk. .,..l0WWWX; .xWMK, .kMM0, .oxkkkKWWMMWWWWx. cKl...:Ko  oWNl  ,OXKl. ,KWl  'kX0;  oWMMk. lNWW
WWWWM0' .kWo. .dWx. '0WO, .coo'  :XWk. .OWNWWk.  . .dXWNWX; .dWWO' .xWWN0xoll;';kWWWWWMMMX; .l',k:.c' '0WX:  cNWWk. .OWl  :NWXc  oWWWKl:OWWW
WWWWW0' .kWXdcxNMx. '0Wx. .col.  :XWk. .OWWWWk. 'xo. 'dXWNl  'll;. .xWW0ccooo;  :XWWWWWWWWx.  .oNx.   oNWWk. .:ol' .lXWl  :NWNc  oWWWOc;dNWW
MMMWWKc,c0WNWWMMWO:,lXMNkc;:cxo,,dWM0c,cKMMWWO:,lXW0l,;dXWXd:;:oxc':0MMNklc;;:cd0NWMMWWNWWNo,,c0WXo,,cKMMMWKdc:;;coONMWk,'dNMWx,;xWMWO:,dNMM
WWWWWWWNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMWWWWWWWWWWWWWWWWWWWWWWWWWWWMWWWWWMWWWWWWWWWWWWWWWWWWWWWWWWW"""